version: "3.9"
services:
  app:
    container_name: app
    build: ./docker/app
    volumes:
      - ./app_data:/workspace

  web:
    container_name: web
    image: nginx:1.21.5-alpine
    ports:
      - 9000:80
    volumes:
      - ./app_data:/workspace
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /workspace

  db:
    container_name: db
    build: ./docker/db
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - mysql.env

volumes:
  db-data: